services:
  - type: web
    name: chatapp
    runtime: node
    plan: starter
    buildCommand: npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
